package com.jake.Kingsmen.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "kingsmen_data")
public class DataModel{
    private int id;
    private String name;
    private int cost;
    private boolean stocked;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public int getId(){
        return this.id;
    }

    @DynamoDBAttribute
    public String getName(){
        return this.name;
    }

    @DynamoDBAttribute
    public int getCost(){
        return this.cost;
    }

    @DynamoDBAttribute
    public boolean getStocked(){
        return this.stocked;
    }
}
